### ISSUE TITLE
v0.1 - OCaml on the BEAM

### ISSUE THREAD

**Issue by ostera** [AbstractMachinesLab/caramel#6]
## Summary

I have not found an easy way to lay out what a release for Caramel should look like, so I'm sketching out this issue with a a big checklist of stuff that I think could be somewhat usable for pure-OCaml modules.

To do this we need:

* **the core type language**, excluding support for the fancier features of the type system (like GADTs, or universal quantification in records), so variants, records, tuples, and type parameters.

* **immutable, functional ocaml**, excluding all the imperative and object-oriented features, and some features like recursive let bindings which have no direct translation to Erlang

* **enough pattern matching** so we can work with all the values allowed by the core type languages

* **support for modules**, but not as first class values, and without functors or inclusions

This could already be enough to write some OCaml on the BEAM successfully. We'll see once we get there. 

## Checklist

To make it easier to keep track of what's what and where we currently are, here's a list of the features that are currently working and missing. Where necessary I'll try to make separate issues and link them here.

### Idioms

- [X] Empty tuple `()` is a common value in OCaml, this is translated to the atom `ok` in Erlang. This is not _entirely_ idiomatic, since some functions  are generated that take for last argument the atom `ok`, but it is much nicer for the returned values.

- [x] OCaml let rec's inside of a module-level function definition should be reported as errors. It is common in OCaml to define a recursive helper function to traverse a value using a default accumulator that is hidden from the user, but we can ask the programmer to move this outside for now. See #13 

- [x] OCaml allows `'` (prime) to be used as part of variable names, so it's not uncommon to see `x` and `x'` and `x''`. The equivalent Erlang would be `X`, `X1`, and `X2`, primarily because the single quote is not a valid character to have in a name. See #15

- [x] OCaml allows shadowing of names, which is not supported in Erlang. so that `let x = 1 in let x = x + 1 in x` yields 2. The equivalent Erlang would crash. See #16

### Module System

The goal here is to support the basic OCaml module system, with its nesting and aliasing to provide a flexible and safe way of structuring large amounts of code. Module interfaces should be allowed to dictate what is exported and what isn't.

- [x] **Modules definitions** -- we treat files as modules, and we can create nested modules. Nested modules will be flattened out into separate Erlang modules namespacing the module names. Modules without exports should generate no Erlang sources.

- [x] **Module interfaces** -- interface files will be respected and anything that is not exported there will not be exported in the generated Erlang source. This applies to both types and functions.

- [X] **Module Declarations** -- only functions will be allowed at the module level. Defining values should be an compilation error.

### Type Language

These are the features of the type-language that I'm aiming to support and compile to Dialyzer specs.

- [x] Type variables
- [x] Phantom types -- should be turned into an unused type-variable that will be properly named with an underscore.
- [x] Variants -- compiled into `constructor_atom` or `{constructor_atom, arg0, arg1,...}`
- [x] Polymorphic Variants
  - [x] Explicit constructors -- compiled into `constructor_atom` or `{constructor_atom, arg0, arg1,...}`
  - [x] Inherited constructors
- [x] Tuples
- [x] Aliases
- [x] Records
- [x] Function types
- [x] Interface files constrain exports of types

### Expressions

The following expressions will be supported on the OCaml side 

- [x] Constant:
  - [x] Integers
  - [x] Characters
  - [x] String -- compiled to Erlang Binary strings
  - [x] Floats
- [x] Values
  - [x] Records -- compiled to Erlang maps
    - [x] Creation
    - [X] Field access
    - [x] Update (See #23)
  - [x] Lists
    - [x] empty list
    - [x] list prepending / consing
  - [x] Tuples
  - [x] Variant constructors -- compiled to tagged tuples with constructor name as atom tag
  - [x] Polymorphic variant
    - [x] constructor without argumetns -- compiled to atom 
    - [x] constructors with arguments -- compiled to tagged tuples with constructor name as atom tag
  - [x] Fun/Function -- compiled to Erlang fun's
- [x] Let Bindings
- [x] Identifiers
  - [x] Make sure all variable names translate to valid Erlang variable names (#15 #16)
- [x] Functions
  - [x] References -- in Erlang there is a difference between passing `F` as a parameter, and passing a reference to a function. Waiting on #10   
  - [x] Local calls (in scope or in module scope)
  - [x] Qualified calls 
  - [x] Lambda calls
- [x] Match expressions
  - [x] Cascading cases (`match x with | 1 | 2 -> true`) -- #9 
- [x] If Expressions -- compiled to case expressions
- [x] Sequencing -- compiled to nested let-bindings with an ignore pattern
- [x] Guards -- see #17 

### Patterns

These are the patterns that we can use on the left side of match branches and function headers.

- [x] Ignore value
- [x] Binding to variables
- [x] Tuple
- [x] List
- [x] Records
- [x] Variants
- [x] Polymorphic variants 
- [x] Exact match

### Foreign Interfaces

- [x] Support for `external`
  - [x] without a name override
  - [x] with name overrides

**Comment by ostera** [comment]
## Checklist

To make it easier to keep track of what's what and where we currently are, here's a list of the features that are currently working and missing. Where necessary I'll try to make separate issues and link them here.

### Idioms

- [X] Empty tuple `()` is a common value in OCaml, this is translated to the atom `ok` in Erlang. This is not _entirely_ idiomatic, since some functions  are generated that take for last argument the atom `ok`, but it is much nicer for the returned values.

- [x] OCaml let rec's inside of a module-level function definition should be reported as errors. It is common in OCaml to define a recursive helper function to traverse a value using a default accumulator that is hidden from the user, but we can ask the programmer to move this outside for now. See #13 

- [x] OCaml allows `'` (prime) to be used as part of variable names, so it's not uncommon to see `x` and `x'` and `x''`. The equivalent Erlang would be `X`, `X1`, and `X2`, primarily because the single quote is not a valid character to have in a name. See #15

- [x] OCaml allows shadowing of names, which is not supported in Erlang. so that `let x = 1 in let x = x + 1 in x` yields 2. The equivalent Erlang would crash. See #16

### Module System

The goal here is to support the basic OCaml module system, with its nesting and aliasing to provide a flexible and safe way of structuring large amounts of code. Module interfaces should be allowed to dictate what is exported and what isn't.

- [x] **Modules definitions** -- we treat files as modules, and we can create nested modules. Nested modules will be flattened out into separate Erlang modules namespacing the module names. Modules without exports should generate no Erlang sources.

- [x] **Module interfaces** -- interface files will be respected and anything that is not exported there will not be exported in the generated Erlang source. This applies to both types and functions.

- [X] **Module Declarations** -- only functions will be allowed at the module level. Defining values should be an compilation error.

### Type Language

These are the features of the type-language that I'm aiming to support and compile to Dialyzer specs.

- [x] Type variables
- [x] Phantom types -- should be turned into an unused type-variable that will be properly named with an underscore.
- [x] Variants -- compiled into `constructor_atom` or `{constructor_atom, arg0, arg1,...}`
- [x] Polymorphic Variants
  - [x] Explicit constructors -- compiled into `constructor_atom` or `{constructor_atom, arg0, arg1,...}`
  - [x] Inherited constructors
- [x] Tuples
- [x] Aliases
- [x] Records
- [x] Function types
- [x] Interface files constrain exports of types

### Expressions

The following expressions will be supported on the OCaml side 

- [x] Constant:
  - [x] Integers
  - [x] Characters
  - [x] String -- compiled to Erlang Binary strings
  - [x] Floats
- [x] Values
  - [x] Records -- compiled to Erlang maps
    - [x] Creation
    - [X] Field access
    - [ ] Update
  - [x] Lists
    - [x] empty list
    - [x] list prepending / consing
  - [x] Tuples
  - [x] Variant constructors -- compiled to tagged tuples with constructor name as atom tag
  - [x] Polymorphic variant
    - [x] constructor without argumetns -- compiled to atom 
    - [x] constructors with arguments -- compiled to tagged tuples with constructor name as atom tag
  - [x] Fun/Function -- compiled to Erlang fun's
- [x] Let Bindings
- [x] Identifiers
  - [x] Make sure all variable names translate to valid Erlang variable names (#15 #16)
- [ ] Functions
  - [x] References -- in Erlang there is a difference between passing `F` as a parameter, and passing a reference to a function. Waiting on #10   
  - [x] Local calls (in scope or in module scope)
  - [x] Qualified calls 
  - [ ] Lambda calls -- currently this prints `f(A, B)` for `f(A)(B)` since it has no way of knowing that `f` has arity 1.
- [x] Match expressions
  - [ ] Support for grouping cases together (`match x with | 1 | 2 -> true`) -- #9 
- [x] If Expressions -- compiled to case expressions
- [x] Sequencing -- compiled to nested let-bindings with an ignore pattern
- [ ] Guards -- any guard expression should work on any pattern match case, except at the function clause level where only guards that compile to BEAM NIFs should be allowed.

### Patterns

These are the patterns that we can use on the left side of match branches and function headers.

- [x] Ignore value
- [x] Binding to variables
- [x] Tuple
- [x] List
- [x] Records
- [x] Variants
- [x] Polymorphic variants 
- [x] Exact match

### Foreign Interfaces

- [x] Support for `external`
  - [x] without a name override
  - [x] with name overrides

**Comment by ostera** [comment]
Aaand we're there. Closing this now.

I'm thinking that the next milestone will include no more work on this particular compilation chain, but rather on the inverse process: parsing and type-checking Erlang.

Thanks @nyaray for the push there to scope things more clearly.
