### ISSUE TITLE
v0.1 - OCaml libraries to manipulate Erlang

### ISSUE THREAD

**Issue by ostera** [AbstractMachinesLab/caramel#7]
## Summary

Caramel currently supports generating Erlang source files from an OCaml typed-tree, and it aims to support type-checking a subset of Erlang using the OCaml type-checker as well.

To do this, we need to have good support of the Standard Erlang language at 3 levels: parsing, AST, and printing.

Parsing for reading the Erlang source files. AST for manipulating the structures (and converting from and to the OCaml ASTs). Printing to generate somewhat idiomatic, human readable `.erl` sources.

The result is a library for working with Erlang sources that is agnostic of the purposes of Caramel itself, and can be used to experiment with the language, build AST-aware transformations, a pretty printer, etc.

While I don't have an intention of doing all of those right now, I'd like to enable the OCaml and BEAM ecosystem to be able to do these things.

## Checklist

The library should contain:

* a definition of an AST for Erlang,
* a parser that follows the [Standard Erlang grammar](https://github.com/erlang/otp/blob/master/lib/stdlib/src/erl_parse.yrl), and
* 2 printers: a debugging S-expr printer, and a Standard Erlang printer

### Language Support

This list and its completeness is a work in progress.

#### Preprocessor Language

- [X] Macro definition
- [X] Macro application

#### Module Language

- [x] Module attributes (built-in and custom ones)
- [x] Type declarations
- [x] Function declarations

#### Type Language

- [x] Opaque types
- [x] Visible types
- [x] Union types
- [x] Aliases
- [x] Record types
- [x] Tuple types
- [x] Map types
- [x] Function types
- [x] Type constructors
- [x] Type variables
- [x] Function specs
- [X] Callback function specs

#### Pattern Language

- [x] Ignore pattern (`_`) -- AST, Printer
- [x] Constant matches (against literals)  -- AST, Printer
- [x] Tuple patterns -- AST, Printer
- [x] List patterns -- AST, Printer
  - [x] Empty list -- AST, Printer
  - [x] Head-tail patterns -- AST, Printer
  - [x] Exact list patterns -- AST, Printer
- [x] Map patterns -- AST, Printer
- [x] Pattern binding -- AST, Printer

#### Expression Language

- [x] Constants:
  - [x] Integer -- AST, Printer
  - [x] Floats -- AST, Printer
  - [x] Binary Strings -- AST, Printer
  - [x] Strings -- AST, Printer
  - [x] IO Lists
  - [x] Characters -- AST, Printer
  - [x] Atoms -- AST, Printer
- [x] Let bindings -- AST, Printer
- [x] Passing Identifiers to other expressions -- AST, Printer
- [x] Function:
  - [x] Fun references -- AST, Printer
  - [x] Lambda application (`F()`) -- AST, Printer
  - [x] Unqualified application (`f()`) -- AST, Printer
  - [x] Qualified application (`m:f()`) -- AST, Printer
  - [x] Dynamic Qualified application (`M:F()`) -- AST, Printer
- [x] Map expressions
  - [x] New map -- AST, Printer
  - [x] Map updates
- [x] List expressions:
  - [x] Empty list -- AST, Printer
  - [x] Lists with elements -- AST, Printer
  - [x] List consing (`[ H | T]`) -- AST, Printer
- [x] Tuple expressions -- AST, Printer
- [X] Exception expressions:
  - [X] Try catch
  - [X] Catch
  - [X] Throw 
- [x] Case expressions -- AST, Printer
- [x] Messaging expressions
  - [x] Receive -- AST, Printer
  - [x] Receive .. After -- AST, Printer
  - [x] Send (although this is just an infix operator for `erlang:send/2`) -- AST, Printer
- [X] Clause Guards

#### Operators

- [X] *
- [X] /
- [X] div
- [X] rem
- [X] band
- [X] and
- [X] +
- [X] -
- [X] bor
- [X] bxor
- [X] bsl
- [X] bsr
- [X] or
- [X] xor
- [X] ++
- [X] --
- [X] ==
- [X] /=
- [X] =<
- [X] <
- [X] >=
- [X] >
- [X] =:=
- [X] =/=
- [X] <=
- [X] =>
- [X] :=
- [X] <<
- [X] >>
- [X] !

**Comment by ostera** [comment]
## Checklist

The library should contain:

* a definition of an AST for Erlang,
* a parser that follows the [Standard Erlang grammar](https://github.com/erlang/otp/blob/master/lib/stdlib/src/erl_parse.yrl), and
* 2 printers: a debugging S-expr printer, and a Standard Erlang printer

### Language Support

This list and its completeness is a work in progress.

#### Preprocessor Language

- [X] Macro definition
- [X] Macro application

#### Module Language

- [x] Module attributes (built-in and custom ones)
- [x] Type declarations
- [x] Function declarations

#### Type Language

- [x] Opaque types
- [x] Visible types
- [x] Union types
- [x] Aliases
- [x] Record types
- [x] Tuple types
- [x] Map types
- [x] Function types
- [x] Type constructors
- [x] Type variables
- [x] Function specs
- [X] Callback function specs

#### Pattern Language

- [x] Ignore pattern (`_`) -- AST, Printer
- [x] Constant matches (against literals)  -- AST, Printer
- [x] Tuple patterns -- AST, Printer
- [x] List patterns -- AST, Printer
  - [x] Empty list -- AST, Printer
  - [x] Head-tail patterns -- AST, Printer
  - [x] Exact list patterns -- AST, Printer
- [ ] Record patterns
- [x] Map patterns -- AST, Printer
- [x] Pattern binding -- AST, Printer

#### Expression Language

- [x] Constants:
  - [x] Integer -- AST, Printer
  - [x] Floats -- AST, Printer
  - [x] Binary Strings -- AST, Printer
  - [x] Strings -- AST, Printer
  - [x] IO Lists
  - [x] Characters -- AST, Printer
  - [x] Atoms -- AST, Printer
- [x] Let bindings -- AST, Printer
- [x] Passing Identifiers to other expressions -- AST, Printer
- [x] Function:
  - [x] Fun references -- AST, Printer
  - [x] Lambda application (`F()`) -- AST, Printer
  - [x] Unqualified application (`f()`) -- AST, Printer
  - [x] Qualified application (`m:f()`) -- AST, Printer
  - [x] Dynamic Qualified application (`M:F()`) -- AST, Printer
- [x] Map expressions
  - [x] New map -- AST, Printer
  - [x] Map updates
- [ ] List expressions:
  - [x] Empty list -- AST, Printer
  - [x] Lists with elements -- AST, Printer
  - [x] List consing (`[ H | T]`) -- AST, Printer
  - [ ] List comprehensions
- [x] Tuple expressions -- AST, Printer
- [ ] Record expressions
  - [ ] New record
  - [ ] Record update
- [X] Exception expressions:
  - [X] Try catch
  - [X] Catch
  - [X] Throw 
- [x] Case expressions -- AST, Printer
- [x] Messaging expressions
  - [x] Receive -- AST, Printer
  - [x] Receive .. After -- AST, Printer
  - [x] Send (although this is just an infix operator for `erlang:send/2`) -- AST, Printer
- [X] Clause Guards

#### Operators

- [X] *
- [X] /
- [X] div
- [X] rem
- [X] band
- [X] and
- [X] +
- [X] -
- [X] bor
- [X] bxor
- [X] bsl
- [X] bsr
- [X] or
- [X] xor
- [X] ++
- [X] --
- [X] ==
- [X] /=
- [X] =<
- [X] <
- [X] >=
- [X] >
- [X] =:=
- [X] =/=
- [X] <=
- [X] =>
- [X] :=
- [X] <<
- [X] >>
- [X] !

**Comment by ostera** [comment]
Postponing support for list comprehensions and records for now. We've got everything we need to support OCaml on the BEAM atm, and a little more. We'll do more work on this for v0.2 as described in #24
