### ISSUE TITLE
v0.1 - Standard Library on the BEAM

### ISSUE THREAD

**Issue by ostera** [AbstractMachinesLab/caramel#8]
## Summary

While #6 is about getting support for a set of OCaml language features, this issue is about putting together a standard library that can be used to interface with the Erlang standard library in a more-or-less idiomatic way.

This likely means 2 things: FFIs and a small runtime library. Some modules might be a combination of both.

### FFIs

In any case, some of these modules will have to break direct compatibility with their Erlang equivalents due to their APIs being uncomfortably unidiomatic OCaml or untypeable in OCaml. 

- [x] `Binary`
  - [x] `at/2`
  - [x] `bin_to_list/1`
  - [x] `copy/2`
  - [x] `decode_unsigned/2`
  - [x] `encode_unsigned/2`
  - [x] `first/1`
  - [x] `last/1`
  - [x] `list_to_bin/1`
  - [x] `replace/4`
  - [x] `split/2`
- [x] `Calendar`
  - [x] `local_time/0`
  - [x] `universal_time/0`
- [x] `Erlang` -- this is actually an ERTS preloaded module
  - [x] `is_atom/1`
  - [x] `is_binary/1`
  - [x] `is_bitstring/1`
  - [x] `is_boolean/1`
  - [x] `is_float/1`
  - [x] `is_integer/1`
  - [x] `is_list/1`
  - [x] `is_map/1`
  - [x] `is_number/1`
  - [x] `is_pid/1`
  - [x] `is_port/1`
  - [x] `is_process_alive/1`
  - [x] `is_reference/1`
  - [x] `is_tuple/1`
  - [x] `length/1`
  - [x] `self/0`
  - [x] `send/2`
  - [x] `spawn/1`
  - [x] `throw/1`
- [x] `Ets`
  - [x] `foldl/3`
  - [x] `foldr/3`
  - [x] `insert/2`
  - [x] `lookup/2`
  - [x] `new/2`
- [x] `Io`
  - [x] `format/2`
- [x] `Lists`
  - [x] `all/2`
  - [x] `any/2`
  - [x] `append/1`
  - [x] `concat/1`
  - [x] `delete/2`
  - [x] `droplast/1`
  - [x] `dropwhile/2`
  - [x] `duplicate/2`
  - [x] `filter/2`
  - [x] `flatmap/2`
  - [x] `flatten/1`
  - [x] `foldl/3`
  - [x] `foldr/3`
  - [x] `foreach/2`
  - [x] `join/2`
  - [x] `last/1`
  - [x] `map/2`
  - [x] `max/1`
  - [x] `member/2`
  - [x] `min/1`
  - [x] `partition/2`
  - [x] `reverse/1`
  - [x] `seq/3`
  - [x] `sort/2`
  - [x] `split/2`
  - [x] `splitwith/3`
  - [x] `sublist/2`
  - [x] `subtract/2`
  - [x] `sum/1`
  - [x] `takewhile/2`
  - [x] `unzip/1`
  - [x] `zip/2`
  - [x] `zipwith/3`
- [x] `Maps`
  - [x] `filter/2`
  - [x] `find/2`
  - [x] `fold/3`
  - [x] `from_list/1`
  - [x] `get/3`
  - [x] `is_key/2`
  - [x] `keys/1`
  - [x] `map/2`
  - [x] `merge/2`
  - [x] `new/0`
  - [x] `put/2`
  - [x] `size/1`
  - [x] `to_list/1`
  - [x] `update/2`
  - [x] `values/1`
  - [x] `with/2`
  - [x] `without/2`
- [x] `Timer`
  - [x] `sleep/1`

### Runtime

These are libraries that actually need the runtime overhead to satisfy some of the type-level constraints.

- [x] `Process` -- as per the experiments i've done on typing message passing, it's likely that we'll need a way to constrain the process types and expose a `receive` function as a stand in for `receive` expressions. This module would implement that runtime overhead.
  - [x] `spawn/2`
  - [x] `contramap/2`
  - [x] `send/2`

**Comment by ostera** [comment]
## Checklist

### FFIs

In any case, some of these modules will have to break direct compatibility with their Erlang equivalents due to their APIs being uncomfortably unidiomatic OCaml or untypeable in OCaml. 

- [x] `Binary`
  - [x] `at/2`
  - [x] `bin_to_list/1`
  - [x] `copy/2`
  - [x] `decode_unsigned/2`
  - [x] `encode_unsigned/2`
  - [x] `first/1`
  - [x] `last/1`
  - [x] `list_to_bin/1`
  - [x] `replace/4`
  - [x] `split/2`
- [x] `Calendar`
  - [x] `local_time/0`
  - [x] `universal_time/0`
- [x] `Erlang` -- this is actually an ERTS preloaded module
  - [x] `is_atom/1`
  - [x] `is_binary/1`
  - [x] `is_bitstring/1`
  - [x] `is_boolean/1`
  - [x] `is_float/1`
  - [x] `is_integer/1`
  - [x] `is_list/1`
  - [x] `is_map/1`
  - [x] `is_number/1`
  - [x] `is_pid/1`
  - [x] `is_port/1`
  - [x] `is_process_alive/1`
  - [x] `is_reference/1`
  - [x] `is_tuple/1`
  - [x] `length/1`
  - [x] `self/0`
  - [x] `send/2`
  - [x] `spawn/1`
  - [x] `throw/1`
- [x] `Ets`
  - [x] `foldl/3`
  - [x] `foldr/3`
  - [x] `insert/2`
  - [x] `lookup/2`
  - [x] `new/2`
- [x] `Io`
  - [x] `format/2`
- [x] `Lists`
  - [x] `all/2`
  - [x] `any/2`
  - [x] `append/1`
  - [x] `concat/1`
  - [x] `delete/2`
  - [x] `droplast/1`
  - [x] `dropwhile/2`
  - [x] `duplicate/2`
  - [x] `filter/2`
  - [x] `flatmap/2`
  - [x] `flatten/1`
  - [x] `foldl/3`
  - [x] `foldr/3`
  - [x] `foreach/2`
  - [x] `join/2`
  - [x] `last/1`
  - [x] `map/2`
  - [x] `max/1`
  - [x] `member/2`
  - [x] `min/1`
  - [x] `partition/2`
  - [x] `reverse/1`
  - [x] `seq/3`
  - [x] `sort/2`
  - [x] `split/2`
  - [x] `splitwith/3`
  - [x] `sublist/2`
  - [x] `subtract/2`
  - [x] `sum/1`
  - [x] `takewhile/2`
  - [x] `unzip/1`
  - [x] `zip/2`
  - [x] `zipwith/3`
- [x] `Maps`
  - [x] `filter/2`
  - [x] `find/2`
  - [x] `fold/3`
  - [x] `from_list/1`
  - [x] `get/3`
  - [x] `is_key/2`
  - [x] `keys/1`
  - [x] `map/2`
  - [x] `merge/2`
  - [x] `new/0`
  - [x] `put/2`
  - [x] `size/1`
  - [x] `to_list/1`
  - [x] `update/2`
  - [x] `values/1`
  - [x] `with/2`
  - [x] `without/2`
- [x] `Timer`
  - [x] `sleep/1`

### Runtime

These are libraries that actually need the runtime overhead to satisfy some of the type-level constraints.

- [x] `Process` -- as per the experiments i've done on typing message passing, it's likely that we'll need a way to constrain the process types and expose a `receive` function as a stand in for `receive` expressions. This module would implement that runtime overhead.
  - [x] `spawn/2`
  - [x] `contramap/2`
  - [x] `send/2`

**Comment by ostera** [comment]
This seems good as it is right now. We'll open a new issue to collect missing FFIs before we tag v0.1
